-- MySQL Script generated by MySQL Workbench
-- Thu May 30 20:53:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS
, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS
, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE
, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myblog
-- -----------------------------------------------------
CREATE SCHEMA
IF NOT EXISTS `myblog` DEFAULT CHARACTER
SET utf8 ;
USE `myblog`
;

-- -----------------------------------------------------
-- Table `myblog`.`articles`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `myblog`.`articles`
(
  `id_article` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR
(120) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `sneak_peek` TEXT NULL,
  `media` VARCHAR
(250) NULL,
  PRIMARY KEY
(`id_article`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`categories`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `myblog`.`categories`
(
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR
(45) NULL,
  PRIMARY KEY
(`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`articles_has_categories`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `myblog`.`articles_has_categories`
(
  `articles_id_article` INT NOT NULL,
  `categories_category_id` INT NOT NULL,
  PRIMARY KEY
(`articles_id_article`, `categories_category_id`),
  INDEX `fk_articles_has_categories_categories1_idx`
(`categories_category_id` ASC) VISIBLE,
  INDEX `fk_articles_has_categories_articles_idx`
(`articles_id_article` ASC) VISIBLE,
  CONSTRAINT `fk_articles_has_categories_articles`
    FOREIGN KEY
(`articles_id_article`)
    REFERENCES `myblog`.`articles`
(`id_article`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_categories_categories1`
    FOREIGN KEY
(`categories_category_id`)
    REFERENCES `myblog`.`categories`
(`category_id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`roles`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `myblog`.`roles`
(
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR
(10) NULL,
  PRIMARY KEY
(`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`users`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `myblog`.`users`
(
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR
(20) NOT NULL,
  `password` VARCHAR
(45) NOT NULL,
  `articles` INT NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY
(`user_id`, `articles`, `role`),
  UNIQUE INDEX `user_id_UNIQUE`
(`user_id` ASC) VISIBLE,
  UNIQUE INDEX `pseudo_UNIQUE`
(`pseudo` ASC) VISIBLE,
  INDEX `fk_users_articles1_idx`
(`articles` ASC) VISIBLE,
  INDEX `fk_users_roles1_idx`
(`role` ASC) VISIBLE,
  CONSTRAINT `fk_users_articles1`
    FOREIGN KEY
(`articles`)
    REFERENCES `myblog`.`articles`
(`id_article`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY
(`role`)
    REFERENCES `myblog`.`roles`
(`role_id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`comments`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `myblog`.`comments`
(
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT NULL,
  `from_article` INT NOT NULL,
  `from_user` INT NULL,
  PRIMARY KEY
(`comment_id`),
  INDEX `fk_comments_articles1_idx`
(`from_article` ASC) VISIBLE,
  INDEX `fk_comments_users1_idx`
(`from_user` ASC) VISIBLE,
  CONSTRAINT `fk_comments_articles1`
    FOREIGN KEY
(`from_article`)
    REFERENCES `myblog`.`articles`
(`id_article`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY
(`from_user`)
    REFERENCES `myblog`.`users`
(`user_id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE
=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS
=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS
=@OLD_UNIQUE_CHECKS;
