-- MySQL Script generated by MySQL Workbench
-- Sun Jun  2 04:15:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS
, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS
, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE
, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `roles`
(
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR
(30) NULL,
  PRIMARY KEY
(`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `users`
(
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR
(70) NOT NULL,
  `pseudo` VARCHAR
(20) NOT NULL,
  `password` VARCHAR
(50) NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY
(`user_id`),
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY
(`role`)
    REFERENCES `roles`
(`role_id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `user_id_UNIQUE` ON `users`
(`user_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `pseudo_UNIQUE` ON `users`
(`pseudo` ASC) VISIBLE;

CREATE INDEX `fk_users_roles1_idx` ON `users`
(`role` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `articles`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `articles`
(
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR
(120) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `sneak_peek` TEXT NULL,
  `author_id` INT NOT NULL,
  `timelog` DATETIME NOT NULL DEFAULT NOW
(),
  PRIMARY KEY
(`id`),
  CONSTRAINT `fk_articles_users1`
    FOREIGN KEY
(`author_id`)
    REFERENCES `users`
(`user_id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `articles`
(`id` ASC) VISIBLE;

CREATE INDEX `fk_articles_users1_idx` ON `articles`
(`author_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `categories`
(
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR
(45) NULL,
  `description` VARCHAR
(45) NULL,
  PRIMARY KEY
(`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comments`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `comments`
(
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT NULL,
  `from_article` INT NOT NULL,
  `from_user` INT NULL,
  `timelog` DATETIME NOT NULL DEFAULT NOW
(),
  `response_to` INT NOT NULL,
  PRIMARY KEY
(`comment_id`),
  CONSTRAINT `fk_comments_articles1`
    FOREIGN KEY
(`from_article`)
    REFERENCES `articles`
(`id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY
(`from_user`)
    REFERENCES `users`
(`user_id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_comments_comments1`
    FOREIGN KEY
(`response_to`)
    REFERENCES `comments`
(`comment_id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_comments_articles1_idx` ON `comments`
(`from_article` ASC) VISIBLE;

CREATE INDEX `fk_comments_users1_idx` ON `comments`
(`from_user` ASC) VISIBLE;

CREATE INDEX `fk_comments_comments1_idx` ON `comments`
(`response_to` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `articles_has_categories`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `articles_has_categories`
(
  `articles_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  CONSTRAINT `fk_articles_has_categories_articles1`
    FOREIGN KEY
(`articles_id`)
    REFERENCES `articles`
(`id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_categories_categories1`
    FOREIGN KEY
(`categories_id`)
    REFERENCES `categories`
(`id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_has_categories_categories1_idx` ON `articles_has_categories`
(`categories_id` ASC) VISIBLE;

CREATE INDEX `fk_articles_has_categories_articles1_idx` ON `articles_has_categories`
(`articles_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `medias`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `medias`
(
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR
(250) NOT NULL,
  PRIMARY KEY
(`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `articles_has_medias`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `articles_has_medias`
(
  `articles_id` INT NOT NULL,
  `medias_id` INT NOT NULL,
  PRIMARY KEY
(`articles_id`, `medias_id`),
  CONSTRAINT `fk_articles_has_medias_articles1`
    FOREIGN KEY
(`articles_id`)
    REFERENCES `articles`
(`id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_medias_medias1`
    FOREIGN KEY
(`medias_id`)
    REFERENCES `medias`
(`id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_has_medias_medias1_idx` ON `articles_has_medias`
(`medias_id` ASC) VISIBLE;

CREATE INDEX `fk_articles_has_medias_articles1_idx` ON `articles_has_medias`
(`articles_id` ASC) VISIBLE;


SET SQL_MODE
=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS
=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS
=@OLD_UNIQUE_CHECKS;
